#!/usr/bin/env bash

nixconf="/etc/nix/nix.conf"
our_cache="https://nixcache.purehs.org"
our_keyname="nixcache.purehs.org.key"
our_key="I56gZt71cbMA6tm8x+1gD6fQyITnE+Q4DgNQIXd7sJg="

if [[ -n $CI ]] ; then
    ./installNix.sh
    sudo sed -i.bak 's|^\(binary-caches[ =].*\)$|\1 '"$our_cache"'|' "$nixconf"
    sudo sed -i.bak 's|^\(binary-cache-public-keys[ =].*\)$|\1 '"$our_keyname"':'"$our_key"'|' "$nixconf"
    sudo killall -9 nix-daemon
    sudo nix-daemon
fi;