#!/usr/bin/env bash

nixconf="/etc/nix/nix.conf"
our_cache="https://nixcache.purehs.org"
our_keyname="nixcache.purehs.org.key"
our_key="I56gZt71cbMA6tm8x+1gD6fQyITnE+Q4DgNQIXd7sJg="

caches_line="binary-caches = https://cache.nixos.org $our_cache"
keys_line="binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= $our_keyname:$our_key"

if [[ -n $CI ]] ; then
    ./installNix.sh
    sudo sed -i.bak 's|^\(binary-caches[ =].*\)$|\1 '"$our_cache"'|' "$nixconf"
    sudo sed -i.bak 's|^\(binary-cache-public-keys[ =].*\)$|\1 '"$our_keyname"':'"$our_key"'|' "$nixconf"
    sudo tee -a "$nixconf" > /dev/null <<EOF
$caches_line
$keys_line
binary-caches-parallel-connections = 40
EOF
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi;