#!/usr/bin/env bash
set -euo pipefail

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. "$DIR/common-setup.sh"

ROOT_PERMISSION_FIX_SUGGESTION="please use your operating system's \"repair permissions\" feature, if it has one, or manually remove write permissions for your user from the '/' directory."

if [ -e /homeless-shelter ] ; then
  echo "It looks like your system has a directory or file at '/homeless-shelter'.  This will cause the devtools build to fail, because the Nix package manager assumes that /homeless-shelter does not exist and cannot be created."
  echo
  echo "If you intentionally created /homeless-shelter, please submit an issue at $REPO/issues, and we will try to find a workaround for this situation.  However, usually, this directory is created by accident when a Nix script is run by a user who has write permissions to the root directory."
  echo
  echo "If this is the case, please remove the /homeless-shelter directory, then ensure that your root directory is not writable by the current user.  To do this, $ROOT_PERMISSION_FIX_SUGGESTION"
  exit 1
elif mkdir /homeless-shelter 2>/dev/null ; then
  rmdir /homeless-shelter
  echo "It looks like your filesystem's root directory is writable by the current user.  This will cause nix to fail building devtools, and may also indicate a security vulnerability.  Note that you should not run devtools as root."
  echo
  echo "To fix this problem, $ROOT_PERMISSION_FIX_SUGGESTION"
  exit 1
fi

echo "Entering the development sandbox..."

INFO=$(cat <<EOF

You are now in a shell with access to Pure development tools.

EOF
)

terminate_logging
try_pure_shell --command "echo \"$INFO\" ; return" "$@"

